version: "3"
services:
  boathouse-calculator-dev:
    environment:
      ROOT_PASSWORD: root123
      LOCAL_USER_PASSWORD: root123     
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-vscode:all-version

    networks:
    - smartide-network
    ports:
    - 3001:3001
    restart: always
    volumes:
    - .:/home/project
networks:
  smartide-network:
    external: true
