apiVersion: apps/v1
kind: Deployment
metadata:
  name: boathouse-calculator
  labels:
    app: boathouse-calculator
spec:
  replicas: 10
  selector:
    matchLabels:
      app: boathouse-calculator
  template:
    metadata:
      labels:
        app: boathouse-calculator
    spec:
      containers:
        - name: boathouse-calculator-dev
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 3001
              protocol: TCP
