apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boathouse-cal-ingress
spec:
  rules:
  - http:
      paths:
      - path: "/cal"
        pathType: Prefix
        backend:
          service:
            name: boathouse-calculator
            port:
              number: 3001